### ISSUE TITLE
Fix decimal_to_percentage() rounding errors in ratio.py

### ISSUE THREAD

**Issue by GriffinAustin** [GriffinAustin/StockEssence#2]
Currently, the function does not account for values that should be rounded, instead it just ignores extraneous decimals

**Comment by GeoZac** [comment]
Increasing the index at https://github.com/GriffinAustin/StockEssence/blob/0cf668387bb4d10ba7d6feb5e3a4ffed933d6d0d/src/ratio.py#L20 will get that done

**Comment by GriffinAustin** [comment]
Hi @GeoZac 

Just checking in to see where you are on this issue.

Thanks

**Comment by GeoZac** [comment]
@GriffinAustin never realised that you were expecting a pull request to resolve the issue,in that case I may be able to do that before weekend,but then I was not satisfied [this](https://github.com/GriffinAustin/StockEssence/blob/0cf668387bb4d10ba7d6feb5e3a4ffed933d6d0d/src/ratio.py#L16) implementation.

**Comment by GriffinAustin** [comment]
@GeoZac I'm thinking we totally eliminate decimal_to_percentage() as a pure decimal for profit margin is more usable and nearly just as readable a rounded percentage. Let me know if you have any conflicting thoughts on the issue.

**Comment by GeoZac** [comment]
@GriffinAustin While a pure decimal is apt in the case of profit margin, the growth rate as mentioned in #13 would be better with percentage

**Comment by GriffinAustin** [comment]
@GeoZac I can understand than from a user standpoint; but if we wanted to reference growth rate for calculations we would either have to store both versions, or convert percentage to decimal. It seems like decimal is far more ubiquitous than percentage in my opinion.
